# Increase memory and *parallel*
org.gradle.jvmargs           = -Xmx6G
org.gradle.parallel          = true

# MonkeyLib538, check at https://github.com/OffsetMods538/MonkeyLib538
monkeylib538_version         = 3.0.0-beta.2.1769880528759+b61667d
# MESH Lib, check at https://github.com/OffsetMods538/MESH-Lib
meshlib_version              = 2.0.0-alpha.0.1769880665236+1a435fc
# JGit
jgit_version                 = 6.9.0.202403050737-r
## JSpecify, check at https://mvnrepository.com/artifact/org.jspecify/jspecify
jspecify_version             = 1.0.0
## Bundeled with Minecraft, common needs to use
guava_version                = 33.4.0-jre
## Bundeled with Minecraft, common needs to use
brigadier_version            = 1.3.10
## Bundeled with Minecraft, common needs to use
commonsio_version            = 2.18.0
## Bundeled with Minecraft, common needs to use
commonslang_version          = 3.18.0
## Bundeled with Minecraft, common needs to use
gson_version                 = 2.11.0
## DevAuth, check at https://github.com/DJtheRedstoner/DevAuth
devauth_version              = 1.2.2

## Gradle plugins
neoforged_moddev             = 2.0.+
fabric_loom                  = 1.15-SNAPSHOT
papermc_paperweight_userdev  = 2.0.0-beta.19
jpenilla_run_task            = 3.0.2
gradleup_shadow              = 9.3.1
jpenilla_resource_factory    = 1.3.1
dexman_outlet                = 1.6.1
modrinth_minotaur            = 2.+

# Mod Properties
mod_version                  = 5.0.0-alpha.0
mod_name                     = Git Pack Manager
mod_id                       = git-pack-manager
mod_description              = Allows for auto-updating resource and data packs at runtime from a git repository.
mod_website                  = https://modrinth.com/mod/git-pack-manager
mod_issues                   = https://github.com/OffsetMods538/Git-Pack-Manager/issues
mod_sources                  = https://github.com/OffsetMods538/Git-Pack-Manager
