# Increase memory and *parallel*
org.gradle.jvmargs              = -Xmx6G
org.gradle.parallel             = true

minecraft_version               = 1.21.4

# MESH Lib, check at https://github.com/OffsetMods538/MESH-Lib
meshlib_version                 = 1.0.5+1.21.4
# MonkeyLib538, check at https://github.com/OffsetMods538/MonkeyLib538
monkeylib538_version            = 3.0.0-992e97c

# Mod Properties
mod_version                     = 5.0.0
supported_minecraft_versions    = >=1.19.2
