site_name: GitHub Resourcepack Manager
repo_name: OffsetMods538/Github-Resourcepack-Manager
repo_url: https://github.com/OffsetMods538/Github-Resourcepack-Manager
edit_uri: /tree/docs/docs
theme:
  name: material
  logo: images/logo.ico
  favicon: images/logo.ico
  features:
    - navigation.tabs
    - navigation.selections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: lime
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OffsetMods538/Github-Resourcepack-Manager
    - icon: fontawesome/brands/discord
      link: https://discord.offsetmonkey538.top

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.betterem
  - pymdownx.keys
  - admonition
  - attr_list

nav:
  - About: index.md
  - Installation: tutorials/installation.md
  - Configuration:
      - GitHub Repository Creation: tutorials/configuration/github-repo-creation.md
      - Mod Configuration: tutorials/configuration/mod-configuration.md
      - GitHub Repository Configuration: tutorials/configuration/github-repo-configuration.md
      - Testing it out: tutorials/testing.md
  - Reference:
      - Pack Update Message Format: reference/update-message.md
      - Pack Priority: reference/priority.md
      - Discord Webhook: reference/discord-webhook.md