site_name: GitHub Resourcepack Merger
repo_name: OffsetMods538/Github-Resourcepack-Manager
repo_url: https://github.com/OffsetMods538/Github-Resourcepack-Manager
edit_uri: /tree/docs/docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.selections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: lime
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OffsetMods538/Github-Resourcepack-Manager
    - icon: fontawesome/brands/discord
      link: https://discord.offsetmonkey538.top

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - admonition
  - attr_list
