pluginManagement {
	repositories {
		maven {
			name = "Fabric"
			url  = "https://maven.fabricmc.net/"
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = "git-pack-manager"


include "common"

include "modded"
include "modded:1.21.1"

include "loader:fabric"
include "loader:fabric:1.21.1"

include "loader:neoforge"
include "loader:neoforge:1.21.1"

include "loader:paper"
include "loader:paper:1.21.1"
