import dex.plugins.outlet.v2.util.ReleaseType

plugins {
    id 'multiloader-neoforge'
}

allprojects {
    neoForgeModsToml {
        mitLicense()
        mod(rootProject.neo_mod_id) {
            authors = "OffsetMonkey538"
            dependencies {
                required("monkeylib538", "[${rootProject.monkeylib538_version},)")
                required("meshlib", "[${rootProject.meshlib_version},)")
            }
        }
        mixin("git-pack-manager.modded.mixins.json")
    }

    dependencies {
        compileOnly "top.offsetmonkey538.monkeylib538:monkeylib538-neoforge:${rootProject.monkeylib538_version}+neoforge"
        compileOnly("top.offsetmonkey538.meshlib:meshlib-neoforge:${rootProject.meshlib_version}+neoforge") {
            exclude(group: "top.offsetmonkey538.monkeylib538")
        }
    }
}

subprojects {
    // Gotta have this here cause I can't import it in buildSrc
    outlet.allowedReleaseTypes = Set.of(ReleaseType.RELEASE)

    dependencies {
        implementation "top.offsetmonkey538.monkeylib538:monkeylib538-neoforge-${project.monkeylib538_suffix}:${rootProject.monkeylib538_version}+neoforge+${project.monkeylib538_suffix}"
        implementation ("top.offsetmonkey538.meshlib:meshlib-neoforge-${project.meshlib_suffix}:${rootProject.meshlib_version}+neoforge+${project.meshlib_suffix}") {
            exclude(group: "top.offsetmonkey538.monkeylib538")
        }

        includeRuntime "org.eclipse.jgit:org.eclipse.jgit:${rootProject.jgit_version}"
    }

    modrinth {
        dependencies {
            required.project "monkeylib538"
            required.project "mesh-lib"
        }
    }
}
