plugins {
	id 'multiloader-modded'
}

allprojects {
	dependencies {
		modCompileOnly("top.offsetmonkey538.monkeylib538:monkeylib538-modded:${rootProject.monkeylib538_version}+modded") {
			exclude(group: "net.kyori")
		}
		modCompileOnly("top.offsetmonkey538.meshlib:mesh-lib-modded:${rootProject.meshlib_version}+modded") {
			exclude(group: "net.kyori")
			exclude(group: "top.offsetmonkey538.monkeylib538")
		}
	}
}

subprojects {
	dependencies {
		modCompileOnly("top.offsetmonkey538.monkeylib538:monkeylib538-modded-${project.monkeylib538_suffix}:${rootProject.monkeylib538_version}+modded+${project.monkeylib538_suffix}") {
			exclude(group: "net.kyori")
		}
		modCompileOnly("top.offsetmonkey538.meshlib:mesh-lib-modded-${project.meshlib_suffix}:${rootProject.meshlib_version}+modded+${project.meshlib_suffix}") {
			exclude(group: "net.kyori")
			exclude(group: "top.offsetmonkey538.monkeylib538")
		}
	}
}
