plugins {
    id 'multiloader-base'
}

repositories {
    maven {
        name = "Mojang Libraries"
        url = "https://libraries.minecraft.net"
        content {
            includeGroup "com.mojang"
        }
    }
}

dependencies {
    compileOnlyApi("top.offsetmonkey538.monkeylib538:monkeylib538-common:${rootProject.monkeylib538_version}+common") {
        exclude(group: "net.kyori")
    }
    compileOnlyApi("top.offsetmonkey538.meshlib:meshlib-common:${rootProject.meshlib_version}+common") {
        exclude(group: "net.kyori")
    }

    compileOnlyApi "net.kyori:adventure-api:${project.adventure_api_version}"
    compileOnlyApi "net.kyori:adventure-text-minimessage:${project.adventure_api_version}"

    api "org.eclipse.jgit:org.eclipse.jgit:${rootProject.jgit_version}"

    // should be bundled with minecraft
    compileOnly "com.mojang:brigadier:${rootProject.brigadier_version}"
    compileOnly "com.google.guava:guava:${rootProject.guava_version}"
    compileOnly "commons-io:commons-io:${rootProject.commonsio_version}"
    compileOnly "org.apache.commons:commons-lang3:${rootProject.commonslang_version}"
    compileOnly "com.google.code.gson:gson:${rootProject.gson_version}"
}
