import dex.plugins.outlet.v2.util.ReleaseType

plugins {
    id 'net.neoforged.moddev' version '2.0.112'
    id 'io.github.dexman545.outlet' version '1.6.1'
}

outlet {
    mcVersionRange = rootProject.supported_minecraft_versions
    allowedReleaseTypes = Set.of(ReleaseType.RELEASE)
}

neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.minecraft_version
    }

    mods {
        "${project.name}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        server {
            server()
        }

        configureEach {
            systemProperty "forge.logging.markers", "REGISTRIES"
        }
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        name = "DevAuth"
        url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1"
        content {
            includeGroup "me.djtheredstoner"
        }
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    api.extendsFrom common

    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    localRuntime "me.djtheredstoner:DevAuth-neoforge:${project.devauth_version}"

    runtimeOnly "top.offsetmonkey538.monkeylib538:monkeylib538-neoforge-1.20.6:${rootProject.monkeylib538_version}+1.20.6"
    compileOnly "top.offsetmonkey538.monkeylib538:monkeylib538-neoforge:${rootProject.monkeylib538_version}"


    runtimeOnly("top.offsetmonkey538.meshlib:mesh-lib-neoforge:${rootProject.meshlib_version}+1.21.4") {
        exclude(group: "top.offsetmonkey538.monkeylib538")
    }

    jarJar(api(project(":common")))
    jarJar(additionalRuntimeClasspath("org.eclipse.jgit:org.eclipse.jgit:${rootProject.jgit_version}"))
}

processResources {
    final Map properties = Map<String, String>.of(
            "modVersion",                 project.mod_version,
            "supportedMinecraftVersions", project.minecraft_version_range,
            "monkeylib538Version",        project.monkeylib538_version,
            "meshLibVersion",             project.meshlib_version
    )

    inputs.properties(properties)

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(properties)
    }

    exclude ".cache/**"
}

modrinth {
    loaders = ["neoforge"]
    //todo idk:_uploadFile = remapJar.archiveFile

    dependencies {
        required.project "monkeylib538"
        // todo idk: required.project "fabric-api"
    }
}