modLoader = "javafml"
loaderVersion = "[1,)"
license="MIT"

issueTrackerURL="https://github.com/OffsetMods538/Github-Resourcepack-Manager/issues"


[[mods]]
modId="git_pack_manager_common"
displayName="Git Pack Manager Common"
version="${modVersion}"
displayURL="https://modrinth.com/mod/github-resourcepack-manager"
authors="OffsetMonkey538"
description="Modify server resourcepack from GitHub"
