project_name                 = fabric-1.21.1
commonModdedVersion          = 1.21.1

monkeylib538_suffix          = 1.21
meshlib_suffix               = 1.21.1

# Minecraft version
minecraft_version            = 1.21.1
# TODO: max version?
supported_minecraft_versions = >=1.21.1

# These should be automatically updated, unless the environment
#  variable "DISABLE_PROPERTIES_UPDATE" is set.
loader_version               = 0.18.4
fapi_version                 = 0.116.8+1.21.1
